spring:
  application:
    name: sistema_bancario

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

app:
  comisiones:
    caja-ahorro: 2000.00
    cuenta-corriente: 5000.00
    cron: "0 0 0 1 * ?" #se ejecuta el 1er día de cada mes a las 12